# Author @mvxt
version: 2.1

#####################
# Common Definitions
#####################

# Orb declarations
orbs:
  heroku: circleci/heroku@1.2.6

# Simple YAML anchors
aliases:
  - &project_dir "~/project"

###### ################
# Workflow definition
###### ################
workflows:
  version: 2.1
  test-and-build-web:
    jobs:
      - test-web
      - build-web-docker:
          context: dart-docker
          requires:
            - test-web

      - deploy-web:
          requires:
            - build-web-docker
          context:
            - heroku
            - dart-docker
  test-and-build-api:
    jobs:
      - test-api
      - build-api-docker:
          context: dart-docker
          requires:
            - test-api
      - deploy-api:
          requires:
            - build-api-docker
          context:
            - heroku
            - dart-docker

##################
# Job Definitions
##################
jobs:
  test-api:
    docker:
      - image: google/dart:2.10.4
    working_directory: "~/project/api"
    steps:
      - checkout:
          path: "~/project"
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
#      - run:
#          name: Run tests
#          command: pub run test --reporter json | tojunit --output test-results/dart-tests/circleci_dart_demo_test-report.xml
#      - store_test_results:
#          path: test-results
  test-web:
    docker:
      - image: google/dart:2.10.4
    working_directory: "~/project/web"
    steps:
      - checkout:
          path: "~/project"
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
#      - run:
#          name: Run tests
#          command: pub run test --reporter json | tojunit --output test-results/dart-tests/circleci_dart_demo_test-report.xml
#      - store_test_results:
#          path: test-results

  deploy-web:
    executor: heroku/default
    steps:
      - deploy-to-heroku:
          image: alive/dart-demo-web
          app-name: dart-web-1
  deploy-api:
    executor: heroku/default
    steps:
      - deploy-to-heroku:
          image: alive/dart-demo-api
          app-name: dart-api-1

  build-web-docker:
    docker:
      - image: cimg/base:2020.08
    working_directory: "~/project/web"
    steps:
      - checkout:
          path: "~/project"
      - build-docker:
          image: alive/dart-demo-web
  build-api-docker:
    docker:
      - image: cimg/base:2020.08
    working_directory: "~/project/api"
    steps:
      - checkout:
          path: "~/project"
      - build-docker:
          image: alive/dart-demo-api

commands:
  dependencies:
    description: "Download dependencies and setup global packages"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
      pub-cache:
        type: string
        default: "~/.pub-cache"
    steps:
      - restore_cache:
          keys:
            - v1.4-dependencies-{{ arch }}-{{ checksum "pubspec.lock" }}
            - v1.4-dependencies-{{ arch }}-
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: pub get
      - run:
          name: Get junitreporter
          shell: << parameters.shell >>
          command: pub global activate junitreport
      - save_cache:
          key: v1.4-dependencies-{{ arch }}-{{ checksum "pubspec.lock" }}
          paths:
            - .dart_tool
            - << parameters.pub-cache >>
  build-docker:
    description: "Build docker image"
    parameters:
      image:
        type: string
    steps:
      - setup_remote_docker
      - run:
          name: Build & tag Docker image
          command: docker build -t << parameters.image >> -t << parameters.image >>:${CIRCLE_SHA1} .
      - run:
          name: Login to DockerHub and push
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push << parameters.image >>
            docker push << parameters.image >>:${CIRCLE_SHA1}
  deploy-to-heroku:
    description: "Deploy to heroku"
    parameters:
      image:
        type: string
      app-name:
        type: string
    steps:
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker
      - run:
          name: Login to Heroku image
          command: heroku container:login
      - run:
          name: Push docker image to Heroku
          command: |
            docker pull << parameters.image >>
            docker tag << parameters.image >> registry.heroku.com/<< parameters.app-name >>/web
            docker push registry.heroku.com/<< parameters.app-name >>/web
      - run:
          name: Release
          command: heroku container:release web -a << parameters.app-name >>
